export const USER_STATE_CHANGE = 'USER_STATE_CHANGE';
export const USER_POST_CHANGE = 'USER_POST_CHANGE';
export const USER_FOLLOWING_CHANGE = 'USER_FOLLOWING_CHANGE';

export const USERS_DATA_CHANGE = 'USERS_DATA_CHANGE';
export const USERS_POST_CHANGE = 'USERS_POST_CHANGE';
export const USERS_LIKE_CHANGE = 'USER_LIKE_CHANGE';
export const USERS_LIKE_COUNT_CHANGE = 'USERS_LIKE_COUNT_CHANGE';

export const CLEAR_DATA = 'CLEAR_DATA';